name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests (shellspec)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Install shellspec
        run: |
          curl -fsSL https://git.io/shellspec | sh -s -- --yes
      - name: Run shellspec tests
        run: /home/runner/.local/bin/shellspec
